version: "3.8"
services:
  # frontend:
  #   image: node:14
  #   working_dir: /app
  #   volumes:
  #     - ./frontend:/app
  #   command: sh -c "npm install && npm audit fix --force && npm run dev"
  #   ports:
  #     - "5173:3000"
  #   depends_on:
  #     - backend
  # backend:
  # image: node:14
  # working_dir: /app
  # volumes:
  #   - ./backend:/app
  # command: sh -c "npm install  && npm run dev"
  # ports:
  #   - "5000:5000"
  # depends_on:
  #   - mysql
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: tasks_db
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
volumes:
  mysql_data:
